title: "FTR Intel - API Testing Documentation"
description: ""

remote_theme: pages-themes/modernist@v0.2.0
plugins:
  - jekyll-remote-theme

# Additional customization
modernist@v0.2.0:
  skin: dark
